### ISSUE TITLE
Failed to initialize the log file - Permission error

### ISSUE THREAD

**Issue by g-yui** [acidicoala/Koalageddon#2]
"Failed opening file C:\ProgramFiles\(x86)\Koalageddon\logs\Integration.EpicGamesLauncher.log for writting: Permission denied"
This happens on All User install, this is due to the Program Files folder being protected, you can't get away from Program File UAC bugs can you? ;)

**Comment by g-yui** [comment]
Basic patch-y solution is to remove the "Read only" flag from just the Koalageddon folder, you could either prompt for UAC everytime someone uses the injector, or bypass UAC entirely, though that would make this even more of a "virus" that it already is 😝 .
Here's some code that may help
```

#include <Windows.h>
#include <iostream>

// Window just goes insane after proper elevation for whatever reason
// To be used as stepping stone :D

int main() {
    wchar_t szPath[MAX_PATH];
    GetModuleFileName(NULL, szPath, ARRAYSIZE(szPath));
        // Launch itself as admin
        SHELLEXECUTEINFO sei = { sizeof(sei) };
        sei.lpVerb = L"runas";
        sei.lpFile = szPath;
        sei.hwnd = NULL;
        sei.nShow = SW_NORMAL;
        if (!ShellExecuteEx(&sei))
        {
            DWORD dwError = GetLastError();
            if (dwError == ERROR_CANCELLED)
            {
                // The user refused to allow privileges elevation.
                std::cout << "User did not allow elevation" << std::endl;
            }
        }
        else
        {
            // The user allowed the privileged elevation
            std::cout << "User gave elevation" << std::endl; 
        }
    return 0;
}
    

```

**Comment by acidicoala** [comment]
That is why I wrote in the Installation instructions:
> 2. Run the installer and complete the installation. **It is recommended to pick a folder other than Program Files since these folders typically require admin access for read/write operations**.

**Comment by g-yui** [comment]
Oh, sorry then!
