### ISSUE TITLE
Batch unlocker for Koalageddon folder

### ISSUE THREAD

**Issue by g-yui** [acidicoala/Koalageddon#3]
I like to install my software on Program Files and as such I've had to manually unlock the folder myself, and I've decided to just make a script to automate it, I would like to share it in case an end-user does not know how to unlock files or for someone who just has no idea why Koalageddon won't launch when installed on a protected folder, and most people don't launch Epic or Steam as Admin, as it happens to the best of us  ;) #2 .

The idea would be that if Koalageddon detects a permission error it could ask for UAC and launch the script to unlock the folder and as such make it more easily accessible, or perhaps just bundle a .bat file and just make the user open it with admin rights. 
Please tell me what you think about it :D

Here's the code:

```
@echo Unlocker for the Koalageddon folder.

@echo off
net.exe session 1>NUL 2>NUL || goto not_admin
echo SUCCESS
goto unlock

:not_admin
echo ERROR: Please run as a local administrator.
timeout 10
exit /b 1

:unlock
:: Since this reg key will change soon, this line will have to change along with it:: 

FOR /F "tokens=2* skip=2" %%a in ('reg query "HKCU\SOFTWARE\acidicoala\Koalageddon" /v "WORKING_DIR"') do SET dir=%%b

IF exist "%dir%" (
icacls "%dir%" /grant everyone:f
echo Folder has been unlocked!
timeout 10
exit /b 1
)

echo Can't find Koalageddon installation, please make sure it's installed and try again.
timeout 5
```
Cheers.

**Comment by acidicoala** [comment]
Hey there, cool script.

Once I have released the new version of Koalageddon (which should be tomorrow evening, hopefully), I suggest you post this script as a `*.bat` file in the forum topic (you may need to zip it). It's better to post the script after the update is released to avoid confusion with registry paths. This way you need to check for the key only under the `HKLM/...` path

Once you have posted the bat file there, I will link to it in the OP, as a note for those who intend to choose `Program Files` as the installation folder and will close this issue.
