### ISSUE TITLE
Injector64 and Injector32 Single-Line error.

### ISSUE THREAD

**Issue by Onasis3314** [acidicoala/Koalageddon#6]
[19:21:31.805] [error]	Expected 2 arguments, received: 0

I receive this error in both the injector64 and injector32 logs.
Is this expected or should I be doing something different?

**Comment by acidicoala** [comment]
This tells me absolutely nothing. You should share all details and all relevant log files if you want help.

**Comment by Onasis3314** [comment]
OH! Forgive me, I'm mentally incapacitated for not reading the readme for the injector <_<.
